---
title: "About this Guide"
author: "[NCCC-170 Group](https://nccc170.org/)"
---



Herein is a guide to particular challenging issues when fitting GLMMs. We have assembled 15 challenges and provided analytical solutions and code examples in SAS and R. These examples are largely drawn from *Generalized Linear Mixed Models* (@stroup_generalized_2024) with some additional examples from real-world analytical issues we have encountered. 

## Examples

1. Negative variance component estimation for block effects for an RCBD experiment. 

1. Overdispersion and choice of inference space and estimation method for count data; and how to handle ripple effects on bias for estimates and inferential statistics. 

1. Covariance structures and bias correction for a completely randomized experiment with repeated measures and a Gaussian response variable. 

1. Covariance structures and bias correction for a CRD with repeated measures and a binomial response variable. Additionally, challenges of choice of inference space: conditional vs. marginal model specification and method of estimation. 

1. RCBD with substantial within-block heterogeneity due to large block size; how to address spatial variability with smoothing splines.

1. How to handle zero-inflated count data including Poisson and negative binomial model. Nonlinear processes,  overdispersion, mixture distribution and choice of inference space and estimation method.

1.  Continuous proportion data with meaningful zeroes and/or ones. Beta hurdle model with random effects. 

1. Ordinal multinomial data (IBD) using a cumulative logit model with random effect and the proportional odds assumption is met.

1. Ordinal multinomial data (RCBD) using a cumulative logit model with random effect and the proportional odds assumption is not met.

1. GLMM-based precision analysis. Comparison between competing designs with same sample size but optimized for different objectives

1. GLMM-based power analyses. 

1. Longitudinal data with time series sine wave regression and standard explanatory covariates. Model with smoothing splines.

1. Repeated measures for zero-inflated data (RCBD). 

1. Special section on interpreting randomized quantile residuals. 


## Contributors:
    
- Nora Bello, *USDA-ARS*        
- Bruce Craig, *Purdue University*        
- Xin Dai, *Utah State University*      
- Susan Durham, *Utah State University* (emerita)        
- Phil Dixon, *Iowa State University*     
- Conor Fair, *University of Georgia*     
- Réka Howard, *University of Nebraska*     
- Clark Kogan, *StatsCraft*     
- Josefina Lacasa, *Kansas State University*      
- Raul Macchiavelli, *University of Puerto Rico*      
- Daniel Palmer, *StatsCraft*       
- Julia Piaskowski, *University of Idaho*  
- Bipin Poudel, *University of Nebraska*  
- Quentin Read, *USDA-ARS*        
- Aaron Rendahl, *University of Minnesota* 
- Walter Stroup, *University of Nebraska* (emeritus)        
- Linda Young, *USDA-NASS* (retired)   

## Acknowledgments

- Multistate Research Project, NCCC170, Research advances in agricultural statistics. 

## License

All data and code used in this website are licensed under  [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.en){.external target="_blank"}. 


